# Generated by Django 5.0.6 on 2024-06-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('provincia', models.CharField(max_length=128)),
                ('estadio', models.CharField(max_length=128)),
                ('rival', models.CharField(max_length=128))
            ],
        ),
    ]
